# Generated by Django 5.2 on 2025-04-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('abbr', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('teams', models.ManyToManyField(to='nbagrid_api_app.team')),
            ],
        ),
    ]
