# Generated by Django 5.2 on 2025-04-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='draft_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='draft_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='draft_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='height_cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='is_greatest_75',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='num_seasons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='weight_kg',
            field=models.IntegerField(default=0),
        ),
    ]
