# Generated by Django 5.2 on 2025-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0002_player_country_player_draft_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_undrafted',
            field=models.BooleanField(default=False),
        ),
    ]
