# Generated by Django 5.2 on 2025-04-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0005_player_career_3gp_player_career_apg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='career_3pa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='career_fga',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='career_fta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='career_gp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='career_gs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='career_high_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='career_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='career_tpg',
            field=models.FloatField(default=0.0),
        ),
    ]
