# Generated by Django 5.2 on 2025-04-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0006_player_career_3pa_player_career_fga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='display_name',
            field=models.CharField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
