# Generated by Django 5.2 on 2025-04-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0007_player_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='display_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
