# Generated by Django 5.2 on 2025-04-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0008_alter_player_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cell_key', models.CharField(max_length=10)),
                ('guess_count', models.IntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbagrid_api_app.player')),
            ],
            options={
                'unique_together': {('date', 'cell_key', 'player')},
            },
        ),
    ]
