# Generated by Django 5.2 on 2025-04-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0009_gameresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_key', models.CharField(max_length=40)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'session_key')},
            },
        ),
    ]
