# Generated by Django 5.2 on 2025-04-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0010_gamecompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('filter_type', models.CharField(max_length=20)),
                ('filter_class', models.CharField(max_length=50)),
                ('filter_config', models.JSONField()),
                ('filter_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'filter_type', 'filter_index')},
            },
        ),
    ]
