# Generated by Django 5.2 on 2025-04-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0011_gamefilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFilterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('filter_type', models.CharField(max_length=10)),
                ('filter_class', models.CharField(max_length=50)),
                ('filter_config', models.JSONField()),
                ('filter_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GameFilter',
        ),
        migrations.AddIndex(
            model_name='gamefilterdb',
            index=models.Index(fields=['date'], name='nbagrid_api_date_97ed02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gamefilterdb',
            unique_together={('date', 'filter_type', 'filter_index')},
        ),
    ]
