# Generated by Django 5.2 on 2025-05-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0013_player_is_award_all_defensive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(help_text="Type of data that was updated (e.g., 'player_data')", max_length=50, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this data was last updated')),
                ('updated_by', models.CharField(blank=True, help_text='Who or what performed the update', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional information about the update', null=True)),
            ],
        ),
    ]
