# Generated by Django 5.2 on 2025-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0014_lastupdated'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGrid',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('grid_size', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell_correct_players', models.JSONField(default=dict)),
            ],
        ),
    ]
