# Generated by Django 5.2 on 2025-05-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0015_gamegrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecompletion',
            name='correct_cells',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamecompletion',
            name='final_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='gamecompletion',
            index=models.Index(fields=['date'], name='nbagrid_api_date_9bb7f0_idx'),
        ),
        migrations.AddIndex(
            model_name='gamecompletion',
            index=models.Index(fields=['final_score'], name='nbagrid_api_final_s_6bb577_idx'),
        ),
    ]
