# Generated by Django 5.2 on 2025-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0016_gamecompletion_correct_cells_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecompletion',
            name='final_score',
            field=models.FloatField(default=0.0),
        ),
    ]
