# Generated by Django 5.2 on 2025-05-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0017_alter_gamecompletion_final_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecompletion',
            name='completion_streak',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamecompletion',
            name='perfect_streak',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='gamecompletion',
            index=models.Index(fields=['completion_streak'], name='nbagrid_api_complet_8e6f96_idx'),
        ),
        migrations.AddIndex(
            model_name='gamecompletion',
            index=models.Index(fields=['perfect_streak'], name='nbagrid_api_perfect_05009b_idx'),
        ),
    ]
