# Generated by Django 5.2 on 2025-05-25 10:41

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0018_gamecompletion_completion_streak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('session_key', models.CharField(help_text='Django session key as primary identifier', max_length=40, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text='Generated display name for the user', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this user data was created')),
                ('last_active', models.DateTimeField(auto_now=True, help_text='When this user was last active')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('userdata'), models.Model),
        ),
    ]
