# Generated by Django 5.2 on 2025-05-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0019_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='base_salary',
            field=models.IntegerField(default=0),
        ),
    ]
