# Generated by Django 5.2 on 2025-05-30 10:00

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0020_player_base_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridMetadata',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('game_title', models.CharField(default='', max_length=40)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('gridmetadata'), models.Model),
        ),
    ]
