# Generated by Django 5.2 on 2025-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0021_gridmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
