# Generated by Django 5.2.4 on 2025-08-06 07:51

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0022_player_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressumContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the impressum section', max_length=200)),
                ('content', models.TextField(help_text='Content text for the impressum section')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this content should be displayed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display in the Impressum modal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impressum Content',
                'verbose_name_plural': 'Impressum Content',
                'ordering': ['order', 'created_at'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('impressum_content'), models.Model),
        ),
    ]
