# Generated by Django 5.2 on 2025-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0023_impressumcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='initial_guesses',
            field=models.IntegerField(default=0),
        ),
    ]
