# Generated by Django 5.2 on 2025-08-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0023_impressumcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='has_made_guesses',
            field=models.BooleanField(default=False, help_text='Whether this user has made at least one guess'),
        ),
    ]
