# Generated by Django 5.2 on 2025-08-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0024_add_initial_guesses_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='wrong_guesses',
            field=models.IntegerField(default=0),
        ),
    ]
