# Generated by Django 5.2 on 2025-08-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0024_userdata_has_made_guesses'),
        ('nbagrid_api_app', '0025_add_wrong_guesses_field'),
    ]

    operations = [
    ]
