# Generated by Django 5.2 on 2025-08-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0026_merge_20250823_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='teammates',
            field=models.ManyToManyField(blank=True, help_text='Players this player has played with on the same team', to='nbagrid_api_app.player'),
        ),
    ]
