# Generated by Django 5.2 on 2025-08-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0027_player_teammates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='last_active',
        ),
    ]
