# Generated by Django 5.2 on 2025-09-03 14:08

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nbagrid_api_app", "0028_remove_last_active_from_userdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(help_text="Django session key for user identification", max_length=40)),
                ("ip_address", models.GenericIPAddressField(blank=True, help_text="IP address of the visitor", null=True)),
                (
                    "source",
                    models.CharField(
                        help_text="Primary traffic source (search_engine, social_media, direct, etc.)", max_length=50
                    ),
                ),
                ("referrer", models.URLField(blank=True, help_text="Full referrer URL", max_length=500, null=True)),
                (
                    "referrer_domain",
                    models.CharField(blank=True, help_text="Extracted referrer domain", max_length=200, null=True),
                ),
                ("utm_source", models.CharField(blank=True, help_text="UTM source parameter", max_length=100, null=True)),
                ("utm_medium", models.CharField(blank=True, help_text="UTM medium parameter", max_length=100, null=True)),
                ("utm_campaign", models.CharField(blank=True, help_text="UTM campaign parameter", max_length=100, null=True)),
                ("utm_term", models.CharField(blank=True, help_text="UTM term parameter", max_length=100, null=True)),
                ("utm_content", models.CharField(blank=True, help_text="UTM content parameter", max_length=100, null=True)),
                ("path", models.CharField(help_text="Requested path/URL", max_length=200)),
                ("query_string", models.TextField(blank=True, help_text="Full query string", null=True)),
                ("user_agent", models.TextField(blank=True, help_text="User agent string", null=True)),
                ("first_visit", models.DateTimeField(auto_now_add=True, help_text="First time this source was recorded")),
                ("last_visit", models.DateTimeField(auto_now=True, help_text="Last time this source was recorded")),
                ("visit_count", models.PositiveIntegerField(default=1, help_text="Number of visits from this source")),
                ("is_bot", models.BooleanField(default=False, help_text="Whether this traffic is from a bot/crawler")),
                (
                    "country",
                    models.CharField(blank=True, help_text="Country of origin (if available)", max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Traffic Source",
                "verbose_name_plural": "Traffic Sources",
                "ordering": ["-last_visit"],
                "indexes": [
                    models.Index(fields=["source"], name="nbagrid_api_source_151d26_idx"),
                    models.Index(fields=["referrer_domain"], name="nbagrid_api_referre_408192_idx"),
                    models.Index(fields=["utm_source"], name="nbagrid_api_utm_sou_509fbc_idx"),
                    models.Index(fields=["utm_campaign"], name="nbagrid_api_utm_cam_5b03da_idx"),
                    models.Index(fields=["first_visit"], name="nbagrid_api_first_v_962d4a_idx"),
                    models.Index(fields=["last_visit"], name="nbagrid_api_last_vi_f1fc4e_idx"),
                    models.Index(fields=["session_key"], name="nbagrid_api_session_e7c69f_idx"),
                ],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin("traffic_source"), models.Model),
        ),
    ]
