# Generated by Django 5.2 on 2025-09-21 11:28, modified for PostgreSQL compatibility

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0029_trafficsource'),
    ]

    operations = [
        # Step 1: Add id fields without making them primary keys yet
        migrations.AddField(
            model_name='gridmetadata',
            name='id',
            field=models.AutoField(null=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gamegrid',
            name='id',
            field=models.AutoField(null=True, serialize=False),
        ),
        
        # Step 2: Remove primary key constraints from date fields
        migrations.AlterField(
            model_name='gridmetadata',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='gamegrid',
            name='date',
            field=models.DateField(unique=True),
        ),
        
        # Step 3: Make id fields the primary keys
        migrations.AlterField(
            model_name='gridmetadata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamegrid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
