# Generated by Django 5.2 on 2025-09-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0029_trafficsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridmetadata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gridmetadata',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
