# Generated by Django 5.2 on 2025-09-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nbagrid_api_app", "0031_change_gamegrid_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamegrid",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="gridmetadata",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="gamegrid",
            name="date",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="gridmetadata",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
