# Generated by Django 5.2 on 2025-10-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbagrid_api_app', '0033_gamegrid_id_gridmetadata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the player is currently active or available for game play'),
        ),
    ]
