{
 "title": "NBAGrid Game Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "User Guesses",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nbagrid_user_guesses_total", "legendFormat": "{{date}}" }
   ]
  },
  {
   "title": "New versus Returning Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(nbagrid_new_users_total[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(nbagrid_returning_users_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wrong Guesses",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "nbagrid_wrong_guesses_total", "legendFormat": "{{date}}" }
   ]
  },
  {
   "title": "Active Games",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nbagrid_active_games", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Visitors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(nbagrid_unique_users_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Games",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "round(increase(nbagrid_game_starts_total[$__range]))",
     "legendFormat": "Games Started"
    },
    {
     "expr": "round(increase(nbagrid_game_completions_total[$__range]))",
     "legendFormat": "Complete Games"
    }
   ]
  }
 ]
}